---
kind: pipeline
type: docker
name: pr_deployment

steps:
- name: build_image
  image: docker:dind
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  environment:
    GCP_DOCKER_BUILDER_KEY:
      from_secret: GCP_DOCKER_BUILDER_KEY
    GCR_PROJECT: savvy-girder-397211
  commands:
  - docker build -t asia-south1-docker.pkg.dev/savvy-girder-397211/pr-repository/pr-image:$DRONE_PULL_REQUEST .
  - echo $GCP_DOCKER_BUILDER_KEY > auth.json
  - echo $(base64 -d auth.json) |  docker login -u _json_key_base64 --password-stdin \
          https://asia-south1-docker.pkg.dev 
  - docker asia-south1-docker.pkg.dev/savvy-girder-397211/pr-repository/pr-image:$DRONE_PULL_REQUEST
- name: deploy_pr
  image: google/cloud-sdk:latest
  environment:
    GCP_DOCKER_BUILDER_KEY:
      from_secret: GCP_DOCKER_BUILDER_KEY
    GCR_PROJECT: savvy-girder-397211
    GCR_REGION: asia-south1
    SERVICE_NAME: pr-
  commands:
  - echo $GCP_DOCKER_BUILDER_KEY | base64 -d > ~/service_account.json
  - gcloud auth activate-service-account --key-file ~/service_account.json
  - gcloud run deploy $SERVICE_NAME$DRONE_PULL_REQUEST --image=asia-south1-docker.pkg.dev/savvy-girder-397211/pr-repository/pr-image:$DRONE_PULL_REQUEST --platform=managed --region=$GCR_REGION --allow-unauthenticated --project=$GCR_PROJECT
  - gcloud run services describe $SERVICE_NAME$DRONE_PULL_REQUEST --region $GCR_REGION --project $GCR_PROJECT --format json > service.json

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock
trigger:
  event:
  - pull_request
  action:
  - opened